#!/usr/bin/env bash

iDIR="/usr/share/icons/Papirus-Dark/symbolic/status/"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl g))
	echo "${LIGHT}"
}

# Get icons
get_icon() {
	current="$(get_backlight)"
	if [[ ("$current" -ge "0") && ("$current" -le "2387") ]]; then
		icon="$iDIR/display-brightness-low-symbolic.svg"
	elif [[ ("$current" -ge "2388") && ("$current" -le "4433") ]]; then
		icon="$iDIR/display-brightness-medium-symbolic.svg"
	elif [[ ("$current" -ge "4434") && ("$current" -le "6818") ]]; then
		icon="$iDIR/display-brightness-high-symbolic.svg"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightnessctl s +5% && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl s 5%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
